PACKAGE_NAME="focaltech-ftexx00"
PACKAGE_VERSION="0.1"

BUILT_MODULE_NAME[0]="focal_spi"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"
MAKE[0]="make KDIR=${kernel_source_dir} KERNELRELEASE=${kernelver}"
